### ISSUE TITLE
BUG: 修改optionData后，手动reloadOptionData不生效

### ISSUE THREAD

**Issue by edwin2jiang** [vform666/variant-form3-vite#10]
## 问题描述：
修改绑定的optionData后，手动调用reloadOptionData不生效。

![image](https://user-images.githubusercontent.com/48372256/181574744-36750384-496a-43fd-bc30-7e81be6a2d2c.png)

## 问题复现
[仓库地址](https://github.com/xia-2/vform-bug-report)

问题复现代码见：
```
/src/views/HomeView.vue
/src/views/VForm.vue
```
使用版本： vform3-builds: ^3.0.8

**Comment by vform666** [comment]
已经修复了，npm包暂时不会升级，你拉取最新源码打包吧：
https://www.yuque.com/visualdev/vform3/ohyr5i
