### ISSUE TITLE
form-designer/setting-panel/index.vue   code redundancy

### ISSUE THREAD

**Issue by leefinder** [vform666/variant-form3-vite#4]
## Version
3.0.6

## Reproduction link
https://github.com/vform666/variant-form3-vite/blob/master/src/components/form-designer/setting-panel/index.vue

## Steps to reproduce
line7 to line 62  
v-if The result is the same

What is expected?
only one el-form is effect

What is actually happening?

> v-if => The result is the same

![image](https://user-images.githubusercontent.com/26495819/164146844-a04d398d-7e20-4bf5-b0ad-ecd4bb80c63e.png)
![image](https://user-images.githubusercontent.com/26495819/164146855-df63e1c3-3d2d-4602-b641-ca5f2c29588a.png)

**Comment by vform666** [comment]
感谢提醒，尽快修复。

**Comment by vform666** [comment]
刚看了源码，el-form如果提到el-tabs外层的话，可能会有问题，form-setting组件内部也有一个el-form。
