### ISSUE TITLE
引入打包的代码控制台报错

### ISSUE THREAD

**Issue by gaoxs1985** [vform666/variant-form3-vite#6]
vite：2.9.12
vue：3.2.37
variant-form3：3.0.8

依照官方文档，进行编译打包后，在新项目引用时控制台报错
![image](https://user-images.githubusercontent.com/2238640/176344779-dd27f24b-ceb6-4436-b06a-33d47a2d77e1.png)

新项目package.json
![image](https://user-images.githubusercontent.com/2238640/176345454-428a5faa-8cfe-43db-b044-4b9c4b6836e8.png)

请问应该如何解决？

**Comment by YangZxi** [comment]
请问你是怎么解决的

**Comment by whhgithub1216** [comment]
请问你是怎么解决的，我也碰到了同样的问题

**Comment by YangZxi** [comment]
> 请问你是怎么解决的，我也碰到了同样的问题

// 默认情况下，不在 node_modules 中的，链接的包不会被预构建。使用此选项可强制预构建链接的包
// https://cn.vitejs.dev/guide/dep-pre-bundling.html#monorepos-and-linked-dependencies
optimizeDeps: {
  include: ['@/../lib/vform3-builds/dist/designer.umd.js'],
  force: true,
}

**Comment by vform666** [comment]
1. 首先，lib目录应该跟src目录平级，lib目录不能放在src目录之内；
2. 其次，按照这个文档配置vite.config.js就可以了：https://www.yuque.com/visualdev/vform3/ohyr5i
